### ISSUE TITLE
進化前精霊の検索除外

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#10]
【重要性】中
【変更度】小
【必要性】
・進化前と進化後の精霊が登録されている場合、これからシミュレーションする人は後者を使う可能性が極めて高い
・cards.jsに後ろに追加していく方式だと、両方ある場合、進化後が下に出る
・ほぼ使わないであろう進化前が表示されているのは邪魔になりうる
・現状ではディートリヒのみだが、将来同様事案が増えると考えられ、明確な方針があるとよい
・再現性確保の観点から、削除せず、検索に出さないような処理実装が必要
【作業予定内容】
・cards.jsにdisable:項目の追加
・デッキ編成画面の検索コードにdisable関連の処理を追加

**Comment by Arika0093** [comment]
作業を行いました。
