### ISSUE TITLE
ASエンハンス＆自傷で、エンハンス対象が自分より前にいない場合自傷が発動しない

### ISSUE THREAD

**Issue by pekko1215** [Arika0093/wiz_simu#146]
ASが「エンハンス＋自傷」の精霊(新人王アマンなど)が、
２番目以降に配置され、前にエンハンス対象の精霊がいない場合、
自傷の効果が発動されない。

**Comment by pekko1215** [comment]
原因はanswer.jsのanswer_enhance関数内で
answer_afterfuncが呼ばれないパターンがある

**Comment by Arika0093** [comment]
暫定修正。 
https://github.com/Arika0093/wiz_simu/commit/afb4dd78aed4e9e4d22fad77eb85dfc86f9c2ce9

Commit Msgにある通り、属性反転などでエンハ対象が0体だとこれでもダメなので
また後で修正が必要。

**Comment by pekko1215** [comment]
エンハンス対象が0体の場合でも自傷が発生するように修正。
8b3d75c

自傷AS発動の条件が今のところチェインのみなので、追加された場合は修正が必要。

**Comment by Arika0093** [comment]
助かります！とりあえずこれで大丈夫そうですね。
