### ISSUE TITLE
ss_chain_cost_skill動作不良

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#16]
【現象】
ss_chain_cost_skillで定義されているSSを使うと、チェイン消費に成功したか否かにかかわらず、
成功した場合としなかった場合両方の効果が発動する

**Comment by konta0112** [comment]
修正しましたが、c_objに新しいオプション（NoRecursion）を追加する必要がありました。別件issue建てます。
101e1d76152be7bc67f631e0fbb173be3a898f7d

**Comment by Arika0093** [comment]
修正ありがとうございました。
こちらの環境で修正を行っていたため、今回はこちらの編集内容を優先させていただきました。次回からは確認を行います。
やった内容はほぼ同じです（遅延評価用のプロパティis_delayをくっつけただけ）。
