### ISSUE TITLE
skill_spe_body.js 記法確認

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#18]
自傷が正常に行われないバグ修正のため、290行目を暫定的に修正しました。
最低限の動作はしますが、
可読性や記法規則の観点において確認修正をお願いします。

**Comment by Arika0093** [comment]
多忙の時期に修正していただきありがとうございました。
こちらの修正内容通り、内部でSpSkill関数を呼び出す際は、
<code>
var sco = ss_consume_own(dmg)
ss_object_done(fld, n, sco);
</code>
というように、まずcards.js用関数でフォーマットを取得し、ついで取得したフォーマットからSpSkillを実行する形に統一することにします。
この書式のメリットは、cards.jsと記法が同様のために修正対応がしやすいことです。
