### ISSUE TITLE
ss_chain_cost定義におけるNoRecursion導入の妥当性検証依頼

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#19]
#16において、チェイン消費でスキル選択する場合、両方が発動していました。
両方のスキルを読み込んだ際再帰的に実行されていることが原因でした。
これを防止するために再帰的実行を禁止するためのプロパティとしてNoRecursionを定義しました。
記法的な問題はないでしょうか？

全部name,type,target,p*に揃えているようなので、
あまり無暗に定義すると収集がつかなくなる恐れがあるかな・・・と。

**Comment by Arika0093** [comment]
ss定義のフォーマットについてですが、好き放題定義しても問題ないです。
むしろ、それを自由にできるようにするためにこういう形式にしたところがあります。
（こういう風にすれば新SS追加が楽だったりするのです）
チェック時は<code>if(!cobj.new_property){ ... } </code>と書けば未定義を弾けます。

長期的なスパンで開発とかはやったことがないので今後のアレな点とかは見なかったことにします。
