### ISSUE TITLE
回復反転 解除不具合

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#26]
回復反転の解除について以下の不具合
・状態異常回復で解除できる
・相手を倒しても解除できない

**Comment by Arika0093** [comment]
回復反転は（主にスキルカウンター用で）適当に組んだのでそうなりました。
仕様です。…とも言ってられないので修正しようかとは思ってます。
倒した時に解除するのがなかなか難しいような気はしますが。

**Comment by konta0112** [comment]
fixed konta/healreverse
