### ISSUE TITLE
精霊検索別ウィンドウで「戻る」をした場合の挙動

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#38]
以下の状態で止まる
・変なタイトル
・画面表示：loading

**Comment by Arika0093** [comment]
その動作は意図しているものです。
非同期処理の最中にwindow.openを仕様するとポップアップブロックされるため、
仕方なくブランクのページを開いています。

解決策は思いつかないです。

**Comment by konta0112** [comment]
語弊がありました。
loading.htmlにエンコードが指定されておらず、多くの環境でShift-JISで表示されます。
その結果タイトルに含まれる漢字が文字化けします。
漢字を使わないかUTF-8と明記するといいと思います。
