### ISSUE TITLE
SP発動ASの配列表記時の挙動

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#48]
SP発動ASはさまざまな種類が存在すると考えられることから、
最大値のみ実行ではなく、定義されているもの全て実行として実装しました。
既存のものとの互換性があまりよくないので、
もし問題があったら修正をお願いします。
（わりと難しいと思います。効果値以外にもパラメータが出たりしそうです。）

**Comment by Arika0093** [comment]
「一般では実行するが特定条件で実行しない」というのがあまり考えられないこと、パラメーターの比較が困難なこと、重複しても影響ないように組むことが可能なことからこの仕様でいこうかと思います。実装ありがとうございました。
