### ISSUE TITLE
AS軽減　バグの恐れ

### ISSUE THREAD

**Issue by konta0112** [Arika0093/wiz_simu#53]
テスト中、精霊にかかっている効果にAS軽減が表示されることありました。
AS軽減は、1Tの間だけかかる、バトルをまたいでも必ずターン消費するターン効果として実装しています。
テスト中なので、前に戻るなどを組み合わせた複雑な操作をしていました。

再現方法は不明です。

**Comment by Arika0093** [comment]
継続効果解除の処理を修正したことにより恐らくですが抑制されたかと思います。
ひとまずcloseします。必要ならreopenしてください。
